/* Generated By:JavaCC: Do not edit this line. SQLCreateParserConstants.java */
package com.mycompany.sql_dbms;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLCreateParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 5;
  /** RegularExpression Id. */
  int TABLE = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int VARCHAR = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int IDENTIFIER = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"CREATE\"",
    "\"TABLE\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "<PRIMARY_KEY>",
    "\"INT\"",
    "\"VARCHAR\"",
    "<NUMBER>",
    "<IDENTIFIER>",
  };

}
